import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/Header";



export const metadata: Metadata = {
  title: "Conura",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <header>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Inter+Tight:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"></link>
      </header>
      <body>
        <Header />


        {children}
      </body>
    </html>
  );
}
